# Generated by Django 6.0 on 2025-12-28 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='difficultyadjustmentlog',
            name='Habit',
        ),
        migrations.AddField(
            model_name='streak',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='difficultyadjustmentlog',
            name='new_difficulty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='difficultyadjustmentlog',
            name='old_difficulty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='streak',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='core.habit'),
        ),
        migrations.AlterUniqueTogether(
            name='streak',
            unique_together={('user', 'habit')},
        ),
        migrations.AddField(
            model_name='difficultyadjustmentlog',
            name='habit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_logs', to='core.habit'),
            preserve_default=False,
        ),
    ]
