# Generated by Django 6.0 on 2025-12-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_difficultyadjustmentlog_habit_streak_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Very Hard'), (5, 'Extreme')], default=1),
        ),
    ]
